# Generated by Django 3.1.4 on 2022-03-07 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titanic',
            options={},
        ),
    ]
